name: Update Homebrew Formula
on:
  release:
    types: [published]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Get release info
        id: release
        run: |
          echo "tag_name=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          echo "tool_name=th" >> $GITHUB_OUTPUT
          VERSION=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Calculate SHA256
        id: sha
        run: |
          TAG="${{ github.event.release.tag_name }}"
          DOWNLOAD_URL="https://github.com/${{ github.repository }}/archive/refs/tags/${TAG}.tar.gz"
          curl -L $DOWNLOAD_URL | shasum -a 256 | cut -d ' ' -f 1 > sha.txt
          echo "sha256=$(cat sha.txt)" >> $GITHUB_OUTPUT
          echo "download_url=$DOWNLOAD_URL" >> $GITHUB_OUTPUT

      - name: Checkout tap repository
        uses: actions/checkout@v3
        with:
          repository: YouLend/homebrew-tools
          token: ${{ secrets.HOMEBREW_PAT_TOKEN }}

      - name: Update formula
        run: |
          FORMULA_FILE="Formula/${{ steps.release.outputs.tool_name }}.rb"
          sed -i 's|url ".*"|url "${{ steps.sha.outputs.download_url }}"|' $FORMULA_FILE
          sed -i 's|sha256 ".*"|sha256 "${{ steps.sha.outputs.sha256 }}"|' $FORMULA_FILE
          sed -i 's|version ".*"|version "${{ steps.release.outputs.version }}"|' $FORMULA_FILE

      - name: Commit and push
        run: |
          git config user.name "${{ secrets.GH_USERNAME }}"
          git config user.email "${{ secrets.GH_EMAIL }}"
          git add Formula/${{ steps.release.outputs.tool_name }}.rb
          git commit -m "Update ${{ steps.release.outputs.tool_name }} formula to ${{ steps.release.outputs.version }}"
          git push
